mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  mvc:
    static-path-pattern: /img/**
  resources:
    static-locations: file:D://upload/
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    master:
      url: jdbc:sqlserver://192.168.1.188:1433;DatabaseName=crop
      username: SAuAzq0dCWqjjKx02QAvCg==
      password: P8yBgUSeARS/u3cGg7SOeMWWgQylZOYR
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      type: com.zaxxer.hikari.HikariDataSource
    cluster:
      - key: slave1
        url: jdbc:sqlserver://192.168.1.188:1433;DatabaseName=TZWZTZW
        username: SAuAzq0dCWqjjKx02QAvCg==
        password: P8yBgUSeARS/u3cGg7SOeMWWgQylZOYR
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        type: com.zaxxer.hikari.HikariDataSource
    aop:
      auto: true
      proxy-target-class: true

whitelist:
  urlList:
    - /authority/login

jwt:
  expire_time: 24 * 60 * 60 * 1000
  expire_time_hour: 24

server:
  port: 9098
